<a href="https://colab.research.google.com/github/DSrahulsah06/MonthlySalaryPrediction-for-Adventure-Works-Cycles/blob/master/Average_Monthly_Salary_Prediction_for_Adventure_Works_Cycles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# Description Of Data
In 1998, the Adventure Works Cycles company collected a large volume of data about their existing customers, including demographic features and information about purchases they have made. The company is particularly interested in analyzing customer data to determine any apparent relationships between demographic features known about the customers and the likelihood of a customer purchasing a bike. Additionally, the analysis should endeavor to determine whether a customer's average monthly spend with the company can be predicted from known customer characteristics.

In [0]:
#importing pakages
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

Using the Adventure Works Cycles customer data you worked to create a regression model that predicts a customer's average monthly spend. The model should predict average monthly spend for new customers for whom no information about average monthly spend or previous bike purchases is available.

In [0]:
dataset = pd.read_csv('gdrive/My Drive/Colab Notebooks/AW_BikeBuyer.csv')
dataset2 = pd.read_csv('gdrive/My Drive/Colab Notebooks/AW_AveMonthSpend.csv')
dataset3 = pd.read_csv('gdrive/My Drive/Colab Notebooks/AdvWorksCusts.csv')

In [0]:
dataset3.drop_duplicates(subset ="AddressLine1", 
                     keep = False, inplace = True) 

In [0]:
#joining bikebuyer dataset with average monthly test spend dataset
df = pd.concat((dataset['CustomerID'],dataset['BikeBuyer'],dataset2['AveMonthSpend']),axis = 1)
df.head()

CustomerID  BikeBuyer  AveMonthSpend
0       11000          0             89
1       11001          1            117
2       11002          0            123
3       11003          0             50
4       11004          1             95

In [0]:
df1 = df.join(dataset3,how='right',lsuffix='_left', rsuffix='_right')
df1.head()

CustomerID_left  BikeBuyer  ...  TotalChildren  YearlyIncome
4             11004          1  ...              5         92771
10            11010          0  ...              0         81294
13            11013          0  ...              2        115859
14            11014          0  ...              3        105157
17            11019          1  ...              0         49455

[5 rows x 26 columns]

In [0]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7678 entries, 4 to 16507
Data columns (total 26 columns):
CustomerID_left         7678 non-null int64
BikeBuyer               7678 non-null int64
AveMonthSpend           7678 non-null int64
CustomerID_right        7678 non-null int64
Title                   42 non-null object
FirstName               7678 non-null object
MiddleName              4414 non-null object
LastName                7678 non-null object
Suffix                  1 non-null object
AddressLine1            7678 non-null object
AddressLine2            138 non-null object
City                    7678 non-null object
StateProvinceName       7678 non-null object
CountryRegionName       7678 non-null object
PostalCode              7678 non-null object
PhoneNumber             7678 non-null object
BirthDate               7678 non-null object
Education               7678 non-null object
Occupation              7678 non-null object
Gender                  7678 non-null object
Ma

In [0]:
#dropping independent variales that do not affect dependent variable
data_new = df1.drop(['CustomerID_left','BikeBuyer','AveMonthSpend','CustomerID_right','Title','FirstName','LastName','MiddleName','Suffix','AddressLine1','AddressLine2','City','StateProvinceName','CountryRegionName','PostalCode','PhoneNumber','BirthDate','Education','Occupation'],axis=1)
data_new.head()

Gender MaritalStatus  ...  TotalChildren  YearlyIncome
4       F             S  ...              5         92771
10      F             S  ...              0         81294
13      M             M  ...              2        115859
14      F             S  ...              3        105157
17      M             S  ...              0         49455

[5 rows x 7 columns]

In [0]:
#storing new data in X and Y 
X = np.array(data_new)
Y = np.array(df1['AveMonthSpend'])

In [0]:
print(X[:,0])
print(X[:,1])

['F' 'F' 'M' ... 'F' 'M' 'M']
['S' 'S' 'M' ... 'S' 'S' 'M']


In [0]:
#label encoding on X to covert Sex and Marital status values into binary
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([0, 0, 1, ..., 0, 1, 1], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
X[:,1]

array([1, 1, 0, ..., 1, 1, 0], dtype=object)

In [0]:
#Creating training datasets
X_train = X 
y_train = df1['AveMonthSpend']

In [0]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)
y_pred_rf=rf.predict(X_train)

In [0]:
from sklearn import metrics
print('Accuracy',metrics.accuracy_score(y_train,y_pred_rf))

Accuracy 0.9996092732482418


In [0]:
#importing test data set
test_data = pd.read_csv('gdrive/My Drive/Colab Notebooks/AW_test.csv')

In [0]:
CustomerID = test_data['CustomerID']

In [0]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
CustomerID              500 non-null int64
Title                   4 non-null object
FirstName               500 non-null object
MiddleName              284 non-null object
LastName                500 non-null object
Suffix                  1 non-null object
AddressLine1            500 non-null object
AddressLine2            13 non-null object
City                    500 non-null object
StateProvinceName       500 non-null object
CountryRegionName       500 non-null object
PostalCode              500 non-null object
PhoneNumber             500 non-null object
BirthDate               500 non-null object
Education               500 non-null object
Occupation              500 non-null object
Gender                  500 non-null object
MaritalStatus           500 non-null object
HomeOwnerFlag           500 non-null int64
NumberCarsOwned         500 non-null int64
NumberChildrenAtHome   

In [0]:
#dropping independent variales that do not affect dependent variables
data_new_test = test_data.drop(['CustomerID','Title','FirstName','LastName','MiddleName','Suffix','AddressLine1','AddressLine2','City','StateProvinceName','CountryRegionName','PostalCode','PhoneNumber','BirthDate','Education','Occupation'],axis=1)
data_new_test.head()

Gender MaritalStatus  ...  TotalChildren  YearlyIncome
0      F             S  ...              5         86931
1      M             M  ...              4        100125
2      F             M  ...              4        103985
3      M             M  ...              4        127161
4      F             M  ...              2         21876

[5 rows x 7 columns]

In [0]:
#storing dataset in Xnew
Xnew = np.array(data_new_test)
Xnew[0:5]

array([['F', 'S', 0, 2, 0, 5, 86931],
       ['M', 'M', 1, 2, 2, 4, 100125],
       ['F', 'M', 1, 2, 0, 4, 103985],
       ['M', 'M', 1, 0, 0, 4, 127161],
       ['F', 'M', 1, 1, 2, 2, 21876]], dtype=object)

In [0]:
#label encoding on Sex and Marital Status
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
Xnew[:,0] = labelencoder_X.fit_transform(Xnew[:,0])
Xnew[:,0]

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
Xnew[:,1] = labelencoder_X.fit_transform(Xnew[:,1])
Xnew[:,1]

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,

In [0]:
# predicting values for Xnew
y_pred = rf.predict(Xnew)
y_pred

array([ 54, 110,  47,  88,  59,  47,  90, 140,  93,  56,  57,  47,  71,
        42,  42,  50,  88,  72,  95,  59,  66,  70, 161,  86,  54,  72,
        87, 123,  75,  58,  65,  84,  43,  71,  98, 107, 170,  94,  58,
        84,  55,  83,  72,  59,  56,  74,  53,  81, 121,  82,  83,  84,
        83,  67,  47,  75,  60,  76,  60,  69,  44,  63,  91,  79,  51,
        76,  77, 148,  63,  99,  82,  78,  94,  47,  66,  73, 126,  67,
        54,  43,  76,  71,  55,  79,  86,  49,  87, 125,  99,  60,  53,
        92,  50,  54,  43, 149,  53,  52,  42,  56, 100,  72,  51, 124,
        86, 107,  35,  49,  52,  58,  92,  48,  76,  64,  74,  89,  45,
        48,  52,  85, 135,  83,  71,  45,  76,  63,  59,  87,  84, 141,
        42,  83, 133,  48,  48, 101, 165,  81,  86,  75,  85,  43, 105,
        37,  69,  55,  59,  42,  59,  67,  91,  68,  70,  72, 103,  47,
        80,  74,  74,  89,  45,  70,  57, 102,  93,  64,  79, 103,  89,
        42,  82,  67,  71,  74,  44,  38, 104,  71,  49, 141,  4

In [0]:
final_data = pd.DataFrame({'CustomerID':CustomerID, 'AvgMonthlySpend':y_pred})
final_data.head()

CustomerID  AvgMonthlySpend
0       18988               54
1       29135              110
2       12156               47
3       13749               88
4       27780               59

In [0]:
final_data.to_csv('gdrive/My Drive/Colab Notebooks/challenge3.5.csv')